# Generated by Django 3.0.4 on 2020-03-12 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permission', '0001_initial'),
        ('school', '0002_auto_20200312_1942'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_group',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AddField(
            model_name='menu_level_3',
            name='parent_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permission.Menu_level_2'),
        ),
        migrations.AddField(
            model_name='menu_level_3',
            name='permission',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Permission'),
        ),
        migrations.AddField(
            model_name='menu_level_2',
            name='parent_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permission.Menu_level_1'),
        ),
        migrations.AddField(
            model_name='menu_level_2',
            name='permission',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Permission'),
        ),
        migrations.AddField(
            model_name='custom_permission',
            name='permission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission'),
        ),
    ]
