# Generated by Django 3.0.4 on 2020-03-12 19:42

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import school.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivateSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_on', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('created_at', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, max_length=200, null=True)),
                ('symbol', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='disable_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=15)),
                ('school_name', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=20)),
                ('contact_no_2', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('no_learner', models.IntegerField()),
                ('country', models.CharField(max_length=300)),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
                ('account_title', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=80, null=True)),
                ('bank_brach', models.CharField(blank=True, max_length=120, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=200, null=True)),
                ('linkdin_url', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='school_docs/')),
                ('document', models.FileField(blank=True, null=True, upload_to='school_docs/')),
                ('other_document', models.FileField(blank=True, null=True, upload_to='school_docs/')),
                ('is_active', models.BooleanField(default=True)),
                ('school_key', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='school_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_therapist', models.BooleanField(default=False)),
                ('is_parent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='school_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=150)),
                ('time', models.DateField()),
                ('state', django_fsm.FSMField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Re Opened', 'Re Opened'), ('Closed', 'Closed')], default=('Open', 'Open'), max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='school_mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_mail', models.BooleanField()),
                ('staff_mail', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='school_services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=100)),
                ('staff_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_no', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('local_address', models.CharField(max_length=300)),
                ('qualification', models.CharField(blank=True, max_length=300, null=True)),
                ('emergency_name', models.CharField(blank=True, max_length=300, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=300, null=True)),
                ('emergency_relation', models.CharField(blank=True, max_length=300, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=300, null=True)),
                ('work_exp', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='staff_docs/image/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='staff_docs/resume/')),
                ('joining_letter', models.FileField(blank=True, null=True, upload_to='staff_docs/joining_letter/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=100)),
                ('internal_no', models.CharField(default=school.models.get_cog_id, editable=False, max_length=100)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(default='images/user.jpeg', upload_to='student_photo/')),
                ('report', models.FileField(null=True, upload_to='student_report/')),
                ('mobileno', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_testuser', models.BooleanField(default=False)),
                ('student_id', models.IntegerField()),
                ('parent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('relation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auth_staff', models.ManyToManyField(db_table='webapp_students_auth_staff', to='school.Staff')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.category')),
            ],
        ),
    ]
