# Generated by Django 3.0.4 on 2020-03-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200312_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='db_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
