# Generated by Django 3.0.4 on 2020-03-24 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('target_allocate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0007_auto_20200319_0725'),
    ]

    operations = [        
        migrations.AlterField(
            model_name='students',
            name='auth_staff',
            field=models.ManyToManyField(to='school.Staff'),
        ),
        migrations.AlterField(
            model_name='students',
            name='diagnoses',
            field=models.ManyToManyField(to='target_allocate.diagnoses'),
        ),
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.FileField(blank=True, default='images/user.jpeg', null=True, upload_to='student_photo/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='students',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='student_report/'),
        ),
    ]
