# Generated by Django 3.0.4 on 2020-03-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20200324_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_location',
            name='state',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
