# Generated by Django 3.0.4 on 2020-03-30 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20200325_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.user_role'),
        ),
    ]
