# Generated by Django 3.0.4 on 2020-03-24 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20200324_0748'),
        ('target_allocate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnoses',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='school.school'),
        ),
    ]
