# Generated by Django 3.0.4 on 2020-03-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('target_allocate', '0002_auto_20200324_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target_allocate',
            name='good_practices',
            field=models.TextField(max_length=200000, null=True),
        ),
        migrations.AlterField(
            model_name='target_allocate',
            name='precaution',
            field=models.TextField(max_length=200000, null=True),
        ),
        migrations.AlterField(
            model_name='target_allocate',
            name='target_instr',
            field=models.TextField(max_length=200000, null=True),
        ),
        migrations.AlterModelTable(
            name='target_type',
            table='target_allocate_target_type1',
        ),
    ]
