"""
Django settings for cogniable_application project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

from datetime import timedelta
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'c$=88wss(nh-uu3^)fe0%b+=%%e-hcp9i=0t9a_^)!q@6anb68'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

COUNTRY_DATABASE = {
    'India' : 'india',
    'United States' : 'usa'
}

DEFAULT_COUNTRY_DATABASE = 'india'
# DJANGO_GROUP_MODEL = 'models.MyGroup'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'school',
    'graphene_django',

    # 'rest_framework_swagger',
	'drf_yasg',
    'rest_framework.authtoken',
    'reversion',
    # 'payroll',
	'channels',
    'chat',
    'follow',
    'django_fsm',
    'river_flow',
    'permission',
    'invoice_and_tickets',
    'corsheaders',
    'superadmin',
    # 'notifications',
    'administrative',
    'behaviour_recording', 
    'target_allocate', 
    'target_recording',
    'online_users',
   # 'rest_messaging',
    'rest_framework',
    'guardian'
   
    
]

CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema' 
   
}

 

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
      }
    },
    'SHOW_REQUEST_HEADERS': True,
     'USE_SESSION_AUTH': True,
    'JSON_EDITOR': False,
}
 
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'rest_messaging.middleware.MessagingMiddleware',

    'online_users.middleware.OnlineNowMiddleware',
    'school.middleware.TimezoneMiddleware',
    'school.middleware.MultiDbRouterMiddleware',
    
     
    
 
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'email-smtp.us-east-1.amazonaws.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'AKIAIBKJ6HGTM3U3QNSQ'
EMAIL_HOST_PASSWORD = 'BKimnTIn0+bqePCFNXID2Y74u060jbseF+milVmWOzxm'

CORS_ORIGIN_ALLOW_ALL = True

# CORS_ORIGIN_WHITELIST = (
#        'http://18.216.56.58',
#        'http://127.0.0.1:8000',
#        'http://127.0.0.1:3000',
#        'http://127.0.0.1:3002',
#        'http://localhost:3002'
# )

from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = default_headers + (
    'Access-Control-Allow-Origin', 'country', 'database',
) 
 
SESSION_ENGINE='school.sessions'

ROOT_URLCONF = 'cogniable_application.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'school.context_processors.multidb_context_processor',  
                'django_base_url.context_processors.base_url' 
            ],
        },
    },
]

 


DATABASE_ROUTERS = ['school.middleware.MultiDbRouter']

AUTHENTICATION_BACKENDS = ('school.backends.CaseInsensitiveModelBackend', 'graphql_jwt.backends.JSONWebTokenBackend',)

GRAPHENE = {
    "SCHEMA": "schema.schema",
    'MIDDLEWARE': [
        # 'school.middleware.TimezoneMiddleware',
        # 'school.middleware.GraphqlMiddleware',
        'graphql_jwt.middleware.JSONWebTokenMiddleware',
    ],
}

DB_EXCEPT_VIEWS = ["Login_Api", "sign_up"]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=50),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': 'Hanuman75@2004',
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id'
 
}

WSGI_APPLICATION = 'cogniable_application.wsgi.application'
ASGI_APPLICATION = "cogniable_application.routing.application"

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# from sshtunnel import SSHTunnelForwarder
# import pymongo
 

# MONGO_HOST = "13.59.192.29"
# MONGO_DB = "new_cogniable"
# MONGO_USER = "ubuntu"
# MONGO_PASS = "cogniable@123"

# server = SSHTunnelForwarder(
#     MONGO_HOST,
#     ssh_username=MONGO_USER,
#     ssh_password=MONGO_PASS,
#     remote_bind_address=('127.0.0.1', 27017)
# )

# server.start()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cogniable3',
        'USER': 'root',
        'PASSWORD': 'Lsa123456',
        'HOST': 'localhost',
        'PORT': '',
         'ATOMIC_REQUESTS': True
         
    },
     'india': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cogniable3',
        'USER': 'root',
        'PASSWORD': 'Lsa123456',
        'HOST': 'localhost',
        'PORT': '',
        'ATOMIC_REQUESTS': True
    }
}


# DATABASES = {
#         'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'new_cogniable',
#         # 'HOST': 'mongodb+srv://cogniable:Lsa123456@cluster0-ucxdc.mongodb.net/test?retryWrites=true&w=majority',
#         # 'USER': 'cogniable',
#         # 'PASSWORD': 'Lsa123456',
#     }
# }


# DATABASE_ROUTERS = ['router.AuthRouter',]

CENTRIFUGO_SECRET_KEY = "fdca39da-47f5-4d76-8cd0-a9fe8ddb22cc"  
CENTRIFUGO_API_KEY = "9c1fb3e2-78fd-42b0-8ad4-6cf5460fe7f0"
CENTRIFUGO_HOST_URL =  "http://127.0.0.1:8081"


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/dj_static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')