const actions = {
  SET_STATE: 'learners/SET_STATE',
  GET_LEARNERS: 'learners/GET_LEARNERS',
  EDIT_LEARNER: 'learners/EDIT_LEARNER',
  CREATE_LEARNER: 'learners/CREATE_LEARNER',
  UPDATE_LERNERS_LIST: 'learners/UPDATE_LERNERS_LIST',
  APPEND_LERNERS_LIST: 'learners/APPEND_LERNERS_LIST',
  GET_LEARNERS_DROPDOWNS: 'learners/GET_LEARNERS_DROPDOWNS',
  LEARNER_ACTIVE_INACTIVE: 'learners/LEARNER_ACTIVE_INACTIVE',
  UPDATE_LEARNER_ACTIVE_INACTIVE: 'learners/UPDATE_LEARNER_ACTIVE_INACTIVE',
}

export default actions
