# Generated by Django 3.0.4 on 2020-03-12 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice_and_tickets', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_fee',
            name='school_services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school_services'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_fee',
            field=models.ManyToManyField(to='invoice_and_tickets.invoice_fee'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_and_tickets.invoice_status'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.students'),
        ),
    ]
