# Generated by Django 3.0.4 on 2020-03-12 19:42

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('state', django_fsm.FSMField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Re Opened', 'Re Opened'), ('Closed', 'Closed')], default=('Open', 'Open'), max_length=50)),
            ],
        ),
    ]
