# Generated by Django 3.0.4 on 2020-03-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0002_auto_20200313_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
